### ISSUE TITLE
[설정파일 만들기]  긁어준 소설 코딩조언 부탁드립니다!!

### ISSUE THREAD

**Issue by codemonkey4578** [taeseong14/N-down#1]
긁어준 소설텍본에 화수를 추가하고 싶습니다 (1화 2화 이렇게)
삽화주소는 삭제하고 싶은데 어떻게 코딩 하면 될까요?
혹시 파이썬으로 전환이 가능할까요?

**Comment by taeseong14** [comment]
화수는 생각하고 있던 문제라 조만간 따리하게 추가하도록 하겠읍니다.

삽화는.. replace로 어케 되지 않을까요
요청 어케 보내면 api단에서 잘 처리해보도록 시도해보겟습니다.

제 주 언어가 js인데도 이걸 golang으로 만든게.. 요청이 너무 느려요
물론 api 구조를 싹 갈아엎으면 안될건 없지만.. 힘들다 보는게 맞을거같습니다.

**Comment by taeseong14** [comment]
화수는 임시로 추가 완료
삽화, 화수 표기, 계정 합쳐서 종합 설정파일 만들예정

**Comment by codemonkey4578** [comment]
exe파일 0.0.5 받아서 실행하는데 자꾸 신규버전받으라고 뜨면서 강제 종료되네요
계정입력까지는 됩니다

**Comment by codemonkey4578** [comment]
New Version Released:[0m ]8;;https://github.com/taeseong14/N-down/releases/tag/v0.0.5\[30;47m0.0.5[0m]8;;\
[30;47m

press enter to exit...[0m
이렇게 뜨네요

**Comment by taeseong14** [comment]
아 제가 .4를 업로드했군요.. 죄송합니다.

그 [0m 이런거 뜨는거는 터미널 또는 윈도우 버전 이슈일 확률이 큽니다.
window 10 또는 높은 버전에서 window powershell로 여는걸 추천드리고요
메인 페이지의 예제처럼 나와야 정상작동 하는거에여


그리고 제목과 별개인 문제 또는 요청은 새 이슈로 달아주세요.

**Comment by taeseong14** [comment]
https://github.com/taeseong14/N-down/releases/tag/v0.1.2
따이
3개월만에 해결한 www
