### ISSUE TITLE
삽화추출 기능추가 건의드립니다

### ISSUE THREAD

**Issue by codemonkey4578** [taeseong14/N-down#13]
혹시 삽화도 같이 jpg 파일로 추출은 불가능할까요?

추출할때 따로 폴더 만들어서 

1화 삽화, 2화 삽화 파일마다 이런식으로 이름 붙게요

공지에 삽화 안올려주는 작가도 있어서요

안해주셔도 상관없습니다!!

**Comment by taeseong14** [comment]
회차 안의 삽화는 [ 이미지: ~~.file ] 로 포함되어 있을텐데요..
크롬으로 여시면 열어집니다.
아님 https://image.online-convert.com/convert-to-jpg  같은걸 써도 되구요

혹시 소설의 표지를 원하시는건가요?

**Comment by codemonkey4578** [comment]
아 그렇군요!!!
표지를 원하지는 않아요
답변해주셔서 감사합니다.
