### ISSUE TITLE
[close: overflow] 프로그램 충돌

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [taeseong14/N-down#15]
높은 챕터 소설을 스크랩할 때 충돌이 발생합니다. 예: 소설 ID =610(2018 챕터). 스크래핑을 완료했지만 txt 파일이 생성되지 않았을 때 충돌이 발생했습니다.

**Comment by taeseong14** [comment]
1000화마다 끊어서 저장하는건 어떨까요?

**Comment by YukinoshitaYukino123** [comment]
네, 좋은 것 같습니다

**Comment by taeseong14** [comment]
의견 감사합니다. 5월 초반까지 완성될 수 있게 하겠습니다.

**Comment by taeseong14** [comment]
먼가 하다보니까 해결된듯 함
https://github.com/taeseong14/N-down/releases/tag/v0.0.8
