### ISSUE TITLE
번역

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [taeseong14/N-down#16]
전체를 번역할 수 있는 방법을 제공할 수 있습니까?  Google 번역은 5000단어로 제한되어 있습니다.  미리 감사드립니다.

**Comment by taeseong14** [comment]
![Snipaste_2023-05-17_15-53-19](https://github.com/taeseong14/N-down/assets/88077395/67a26f54-3c80-4597-a5b1-879ad8edf2ff)
어따쓰게요

**Comment by YukinoshitaYukino123** [comment]
매우 감사합니다

**Comment by taeseong14** [comment]
어따쓰게요..
