### ISSUE TITLE
로그인

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [taeseong14/N-down#19]
갑자기 어제부터 항상 로그인 프로세스에 갇혀 있고 프로그램이 항상 강제 종료됩니다.
![image](https://github.com/taeseong14/N-down/assets/128869659/019830e2-7934-4cc2-963a-42273d8ecf99)

**Comment by taeseong14** [comment]
메인페이지 공지 참고.

**Comment by taeseong14** [comment]
해결☆

**Comment by YukinoshitaYukino123** [comment]
그래서 경고는 우리가 한 번에 너무 많은 소설을 다운로드해서는 안된다는 것을 의미합니까?

**Comment by taeseong14** [comment]
창을 여러개 띄워서 동시에 받지만 않으면 상관 없습니다. 감사합니다

**Comment by YukinoshitaYukino123** [comment]
정보 주셔서 감사합니다
