### ISSUE TITLE
다운로드한 .txt 파일의 css

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [taeseong14/N-down#22]
다운로드한 소설의 임의의 <b></b> 및 <i></i>

**Comment by taeseong14** [comment]
If you want me to fix it first give me novel num you tried and exact issue. If you feel more comfortable in english just say it in english

**Comment by YukinoshitaYukino123** [comment]
ok, the novel id example : 178143
![image](https://github.com/taeseong14/N-down/assets/128869659/fc51eca2-3a24-46c6-aca0-90ba0e6cff8c)
chapter 10
![image](https://github.com/taeseong14/N-down/assets/128869659/e175fd65-2b62-4f0f-967b-69099bec41bd)
chapter 17

another novel id example : 194093
![image](https://github.com/taeseong14/N-down/assets/128869659/e1c17052-555c-4034-add3-d9ed98e5e8d4)
chapter 1 (there's also img style too)

**Comment by taeseong14** [comment]
https://github.com/taeseong14/N-down/releases/tag/v0.1.0 
fixed. thanks for making issue
