### ISSUE TITLE
Issue with login

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [taeseong14/N-down#23]
Is there's an ip ban again? yesterday I was able to download but today I can't login, thanks

**Comment by taeseong14** [comment]
It seems like it works very well for me

**Comment by YukinoshitaYukino123** [comment]
I've tried logging from another device with another internet connection but the result are the same, stuck on login phase and then forced close

**Comment by YukinoshitaYukino123** [comment]
Update: today I'm able to login again
