### ISSUE TITLE
파일 가장 앞에 줄거리 추가

### ISSUE THREAD

**Issue by teril43** [taeseong14/N-down#28]
파일을 열었을 때 가장 앞부분에

소설 줄거리가 출력되면 좋을 것 같은데요.

제목 만으로는 내용을 잊는 경우가 생기는데 있으면 많이 편함

**Comment by taeseong14** [comment]
설정에 추가해보겠읍니다.

**Comment by taeseong14** [comment]
줄거리라는게 여깄는걸 말하시는?
![Snipaste_2023-07-11_13-01-39](https://github.com/taeseong14/N-down/assets/88077395/b3bac8b5-d821-471b-9824-8c06235b6039)

**Comment by taeseong14** [comment]
가져오려면 서버 api도 수정해야해서.. 7월 안쪽으로 작업하도록 해보겠습니다.

**Comment by teril43** [comment]
어 생각보다 대작업... 감사합니다

**Comment by taeseong14** [comment]
https://github.com/taeseong14/N-down/releases/tag/v0.1.4
