### ISSUE TITLE
Login with cookies

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [taeseong14/N-down#29]
After yesterday update I'm unable to login with loginkey anymore (I use gmail login) it give me this error

Error:←[0m ←[91mnot social account←[0m
←[30;47m

**Comment by taeseong14** [comment]
That error means your account with loginkey is not 'social account' [account from other sites(google, naver..)]
Since that step is much complex and error-prone, yesterday I blocked logining with invalid or unsocial(?) loginkey. Sorry for that error but probably you can simply try login with id-pw.
