### ISSUE TITLE
Hello,👋

### ISSUE THREAD

**Issue by larp211** [taeseong14/N-down#3]
한국 이외의 지역에 있는 사람들에게는 19+ 인증이 매우 어려울 수 있습니다. 이를 건너뛸 수 있는 방법이 있을까요? 
Is there a way to bypass the verification process for 19+ since it can be challenging for individuals who are not in Korea to confirm their age?

**Comment by taeseong14** [comment]
저도 해외 사는지라 무슨말인지는 알지만.. 아쉽게도 성인인증 정보는 내부DB에 저장되고 내부적으로만 처리되기 때문에 해킹이 아니면(?) 불가능합니다.

**Comment by larp211** [comment]
> 



> 저도 해외 사는지라 무슨말인지는 알지만.. 아쉽게도 성인인증 정보는 내부DB에 저장되고 내부적으로만 처리되기 때문에 해킹이 아니면(?) 불가능합니다.

"저는 작은 나라에 살고 있고, 이전에 해외를 방문한 적이 없어서 인증된 계정을 만들기 위한 여권이 없습니다. 게다가, 이것이 제 깃허브 사용 첫 경험입니다. 그래도 답변해 주셔서 감사합니다."
