### ISSUE TITLE
Unable to get new episode/chapter

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [taeseong14/N-down#33]
←[1;36mNovelpia Downloader by taeseong14←[0m ←[38;5;244mv0.1.4←[0m ←]8;;https://github.com/taeseong14/N-down←\←[30;47m[Github]←[0m←]8;;←\
←[48;5;16m
[Login]

←[0m←[93mlogin with ←[0m ←[36@←[0m...
login success←[0m
←[95m
bookId: ←[0m69138
[←[36m주인공인데 주인공이 아님←[0m - ←[92m청시앙←[0m] is right? (y/n): y

last ep: 0
Get page. 1/1←[32m [100%]

←[0m←[91mNo new episode←[0m
←[30;47m

press enter to exit...←[0m

it always give this error now, even if I enter another book id

**Comment by taeseong14** [comment]
Error in server. Fixed. ma bad
