### ISSUE TITLE
표지 다운로드?

### ISSUE THREAD

**Issue by kuroka3** [taeseong14/N-down#38]
표지도 같이 다운로드해서 (소설번호 또는 제목).png 또는 (소설번호 또는 제목)/thumb.png로 저장되면 좋을듯??

**Comment by taeseong14** [comment]
근데 보통 1화 처음에 표지 링크가 들가있는데요
그거 들어가면 .file 파일 주니까 #13 참고해서 png/jpg같은걸로 바꿔쓰시거나 크롬에서 열면 열어져요
