### ISSUE TITLE
앱 실행시 로그인 방식 변경에 대한 의견

### ISSUE THREAD

**Issue by kuroka3** [taeseong14/N-down#39]
최초 로그인 한번 후 파일에 로그인 키를 저장해둬 실행시 로그인 키가 유효한지 확인 후 유효하면 추가 로그인 없이 해당 키를 사용하고, 유효하지 않으면 추가 로그인 요청을 보내도록 코드를 변경하면 좋지 않을까요?
로그인 요청이 자주 필요하지 않아서 서버의 부담도 줄어들듯.

**Comment by kuroka3** [comment]
아 이미 login_with_cookie가 있구나
README에 10분 로그인 제한 해결법에 추가해주십셔

**Comment by taeseong14** [comment]
함정) 그건 소셜 연동 계정만 가능하다
그거 생각해본적은 많은데 귀찮아요
