### ISSUE TITLE
다른 방법(구글 연동 등)으로 로그인

### ISSUE THREAD

**Issue by taeseong14** [taeseong14/N-down#4]
ㅈㄱㄴ

**Comment by taeseong14** [comment]
이거 사실 유저가 로그인키만 갖고오게 시키면 되는데 귀찮거든요.

**Comment by jinhons** [comment]
헉헉 기다리고 있겠습니다...로그인키를 가져오게 해야한다면 방법만 알려주시면 가져다 넣겠습니다ㅠㅠ

**Comment by taeseong14** [comment]
음.. 설정에서 로그인키로 로그인하는걸로 바꿀수 있는 옵션 추가하거나 해볼게요

**Comment by taeseong14** [comment]
https://github.com/taeseong14/N-down/releases/tag/v0.1.3
