### ISSUE TITLE
Fail to load novel information

### ISSUE THREAD

**Issue by HeavenlyNover** [taeseong14/N-down#41]
When fetching novel, the line: 소설 정보를 불러올 수 없음 occurs, on newer chapters, for example, it would say:
[20]
Error: 소설 정보를 불러올 수 없음

Also when trying it occurs: Error: too many login reqs. wait for 371sec

**Comment by taeseong14** [comment]
checking on that

**Comment by taeseong14** [comment]
진짜 왠지 모르겠음 js로 파싱하거나 하면 다 잘 되는데. 필요한 헤더나 쿠키도 없고..

**Comment by heski0709** [comment]
저는 user-agent 수정 해보니 잘되네요

**Comment by taeseong14** [comment]
fixed: https://github.com/taeseong14/N-down/releases/tag/v0.1.5

**Comment by taeseong14** [comment]
Also for second error it was delay to reduce the load on the server, changed to 300s.
