### ISSUE TITLE
오류 수정요청 및 작동문의

### ISSUE THREAD

**Issue by codemonkey4578** [taeseong14/N-down#7]
아이디는 입력이 되는데 패스워드가 입력이 안되네요.

exe파일을 그냥 실행하면 cmd로 실행이 되는데 power shell로 실행하는 방법이 따로 있을까요?

**Comment by codemonkey4578** [comment]
아 안보이기만하지 잘 입력 되네요 작업해주셔서 감하합니다 ㅎㅎ

**Comment by taeseong14** [comment]
사실 pw쪽은 다듬고 있었는데 깜빡하고 올려버린 www

**Comment by taeseong14** [comment]
우클릭 -> 다른 머시기로 열기 해서 보면 있을수도요?
없으면 마소스토어나 어디서 다운받으시면 될듯
