### ISSUE TITLE
다운이 안되는 소설들이 좀 있습니다

### ISSUE THREAD

**Issue by jsh3161** [taeseong14/N-down#9]
번거로우실까봐 따로 말씀 안 드리고 있었는데
초기버전부터 특정 몇몇 소설은 계속 다운 안됐었습니다
개선점 이슈에 올리라고 하시니 올리겠습니다
아마 다른소설들과 기본 주소가 다른지 회차 정보부터 못가져옵니다 
기억나는 거는 440번 입니다

**Comment by taeseong14** [comment]
어쩐지 서버에서 가끔 오류가 나더라니.. 
제보해주셔서 감사합니다.

조만간 고치도록 하겠습니다.

**Comment by taeseong14** [comment]
https://github.com/taeseong14/N-down/releases/tag/v0.0.7
해결 완료
감사합니다.
